### ISSUE TITLE
core dump: already port used

### ISSUE THREAD

**Issue by nayuta-ueno** [nayutaco/ptarmigan#1365]
tag: 2019-04-22

既にポートが使用中の場合、`ptarmd`を起動するとcoreを吐く。
jsonrpc-cが起動していないのにjsonrpc-cのstopをしようとするためのようであった。

**Comment by nayuta-ueno** [comment]
```
(gdb) bt
#0  ev_break (loop=0x0, how=2) at ev.c:3709
#1  0x0000559590f0937e in ev_unloop ()
#2  0x0000559590f0a417 in jrpc_server_stop ()
#3  0x0000559590e45779 in cmd_json_stop () at cmd_json.c:238
#4  0x0000559590e39124 in ptarmd_stop () at ptarmd.c:264
#5  0x0000559590e3afb7 in p2p_listener_start (pArg=0x0) at p2p.c:365
```
